#!/bin/bash

SCRIPT_HOME="$(dirname $BASH_SOURCE | sed 's:^\.$:'"$PWD"':g')"
[ ! -z "$CLOUD_SHELL" ] && ENV=cloud || ENV=mac
source ./env/env.sh $ENV

function setup_workspace(){
  if [[ ! -d $WORKSPACE ]]
  then
    mkdir -p $WORKSPACE
  fi
}

function setup_mount(){
  if [[ ! -d $MOUNT ]]
  then
    mkdir -p $MOUNT
  fi
}

function run(){
  docker run --name java-dev-env \
                   --rm \
                   --tty \
                   --env TERM=screen-256color-bce \
                   --interactive \
                   --volume /home/developer/.vim \
                   --volume $WORKSPACE:/home/developer/workspace:rw \
                   --volume $MOUNT:/home/developer \
                   --volume $SSH:/home/developer/.ssh:ro \
                   --volume $DOCKER_SOCKET:/var/run/docker.sock \
                   edwardmlyte/developer-environment:latest
}

setup_workspace
setup_mount
run
